# Render deploy instructions
services:
  - type: web
    name: mechanic-report-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: FLASK_ENV
        value: production
